/* EJERCICIO DE COMPRAS*/

select * from FACTURAS;
select * FROM items_facturas;

SELECT F.DNI, date_format(F.FECHA_VENTA, '%m - %Y') AS FECHA, 
SUM(IFa.CANTIDAD) AS ACUMULADO
FROM FACTURAS F
INNER JOIN ITEMS_FACTURAS IFa
ON F.NUMERO = IFa.NUMERO
group by F.DNI, date_format(F.FECHA_VENTA, '%m - %Y');

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
TC.VOLUMEN_DE_COMPRA/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A;


/*VENTAS INVALIDAD AL 150% SUPERADAS*/ 
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, round(((A.CANTIDAD_VENDIDA/A.CANTIDAD_MAXIMA)*100),2) AS PORCENTAJE_VENTAS
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
TC.VOLUMEN_DE_COMPRA/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
WHERE year(F.FECHA_VENTA) = 2018
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) >0 AND ((A.CANTIDAD_VENDIDA/A.CANTIDAD_MAXIMA)*100) > 150;


/*VENTAS SABOR 2016*/
SELECT P.SABOR, SUM(I.CANTIDAD), YEAR(F.FECHA_VENTA) AS ANUALIDAD FROM tabla_de_productos P
inner join
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
inner join
facturas F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
group by P.SABOR, YEAR(F.FECHA_VENTA)
order by SUM(I.CANTIDAD) desc;

/*VENTAS 2016*/
SELECT SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS ANUALIDAD FROM items_facturas I
inner join
facturas F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
group by YEAR(F.FECHA_VENTA);

SELECT VENTAS_TAMANO.TAMANO, VENTAS_TAMANO.CANTIDAD_LITROS, ROUND(((VENTAS_TAMANO.CANTIDAD_LITROS/VENTAS_TOTALES.CANTIDAD_TOTAL)*100),2) AS PORCENTAJE
FROM 
(SELECT P.TAMANO, SUM(I.CANTIDAD) AS CANTIDAD_LITROS, YEAR(F.FECHA_VENTA) AS ANUALIDAD FROM tabla_de_productos P
inner join
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
inner join
facturas F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
group by P.TAMANO, YEAR(F.FECHA_VENTA)
order by SUM(I.CANTIDAD) desc) VENTAS_TAMANO
INNER JOIN
(SELECT SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS ANUALIDAD FROM items_facturas I
inner join
facturas F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
group by YEAR(F.FECHA_VENTA)) VENTAS_TOTALES
ON VENTAS_TAMANO.ANUALIDAD = VENTAS_TOTALES.ANUALIDAD
ORDER BY PORCENTAJE DESC;