use jugos;

create table REGISTRO_CLIENTES(
DNI VARCHAR (20),
NOMBRE VARCHAR (50),
DIRECCION1 VARCHAR (50),
DIRECCION2 VARCHAR (50),
BARRIO VARCHAR (20),
CIUDAD VARCHAR (20),
ESTADO VARCHAR (20),
CP VARCHAR (10),
EDAD SMALLINT,
SEXO VARCHAR (1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT(1));

CREATE TABLE tabla_vendedores(
MATRICULA VARCHAR(5),
NOMBRE VARCHAR(100),
PORCENTAJE_COMISION DECIMAL);
CREATE TABLE TABLA_DE_VENDEDORES2 (
    MATRICULA varchar(5), 
    NOMBRE varchar(100), 
    PORCENTAJE_COMISION float);
    
alter table PRODUCTOS add primary key (producto);